---
kind: ConfigMap
apiVersion: v1
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: "{{ .Values.name }}-configmap"
data: 
  use-insecure-cookies: {{ .Values.useInsecureCookies | quote }}
  {{ if .Values.usePostgresContainer }}
  postgres-port: "5432"
  postgres-host: "{{ .Values.name }}-postgres"
  postgres-db: "hammerhead_production"
  postgres-user: "retool_internal_user"
  {{ else }}
  postgres-host: {{ .Values.postgresHost | quote }}
  postgres-port: {{ .Values.postgresPort | quote }}
  postgres-db: {{ .Values.postgresDb | quote }}
  postgres-user: {{ .Values.postgresUser | quote }}
  {{ end }}

  {{ if .Values.googleClientId }}
  google-client-id: {{ .Values.googleClientId | quote }}
  {{ else }}
  google-client-id: ""
  {{ end }}
