apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-secret"
type: Opaque
data:
  license-key: {{ .Values.licenseKey | b64enc | quote }}

  {{ if .Values.postgresPassword }}
  postgres-password: {{ .Values.postgresPassword | b64enc | quote }}
  {{ else  }}
  postgres-password: {{ randAlphaNum 20 | b64enc | quote }}
  {{ end }}

  {{ if .Values.retoolJwtSecret }}
  jwt-secret: {{ .Values.jwtSecret | b64enc | quote }}
  {{ else  }}
  jwt-secret: {{ randAlphaNum 20 | b64enc | quote }}
  {{ end }}

  {{ if .Values.encryptionKey }}
  encryption-key: {{ .Values.encryptionKey | b64enc | quote }}
  {{ else  }}
  encryption-key: {{ randAlphaNum 20 | b64enc | quote }}
  {{ end }}

  {{ if .Values.googleClientSecret }}
  google-client-secret: {{ .Values.googleClientSecret | b64enc |quote }}
  {{ else  }}
  google-client-secret: "" 
  {{ end }}
